WIP: Update dependencies
dbmdz/blueprints pull request #163
Opened 2020-08-31 12:07 UTC by schmika

Update dependencies and replace monitoring and code style solutions that are no longer used.
Specifically, remove jolokia and javamelody, replace checkstyle with fmt-maven-plugin.

2020-09-02 10:32 UTC, datazuul requested changes

2020-09-02 10:32 UTC, datazuul commented on webapp-springboot-thymeleaf/doc/README-11-Unit_testing.md
> -    <!-- Exclude JUnit 4 -->
ich denke, man sollte folgende Exclusion machen:

`<exclusions>
        <exclusion>
          <groupId>org.junit.vintage</groupId>
          <artifactId>junit-vintage-engine</artifactId>
        </exclusion>
      </exclusions>`

damit man keine unnötigen juni4 jars auf dem classpath hat

2020-09-02 10:32 UTC, datazuul commented on webapp-springboot-thymeleaf/doc/README-11-Unit_testing.md
> +  <version.maven-failsafe-plugin>3.0.0-M5</version.maven-failsafe-plugin>
version 3 hatte mal probleme gemacht, da dann die integration tests nicht mehr liefen. funktioniert alles noch?

2020-09-02 10:32 UTC, datazuul commented on webapp-springboot-thymeleaf/step10/pom.xml
> +    <version.javamelody-spring-boot-starter>1.85.0</version.javamelody-spring-boot-starter>
sollte javamelody nicht gelöscht werden?

2020-09-02 11:50 UTC, schmika commented on webapp-springboot-thymeleaf/doc/README-11-Unit_testing.md
> +  <version.maven-failsafe-plugin>3.0.0-M5</version.maven-failsafe-plugin>
Danke für den Hinweis, die Tests laufen nach wie vor.

2020-09-03 07:21 UTC, datazuul approved these changes

2020-09-03 07:21 UTC, merged